# Generated by Django 6.0.3 on 2026-03-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField()),
                ('fuente', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('ciudad', models.CharField(max_length=100)),
                ('tipo_violencia', models.CharField(blank=True, choices=[('fisica', 'Violencia Física'), ('psicologica', 'Violencia Psicológica'), ('sexual', 'Violencia Sexual'), ('economica', 'Violencia Económica'), ('otros', 'Otros')], max_length=20)),
                ('nivel_riesgo', models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10)),
                ('verificada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
