# Generated by Django 6.0.3 on 2026-03-27 19:24

import re
import unicodedata

from django.db import migrations, models


def poblar_nuevos_campos(apps, schema_editor):
    Noticia = apps.get_model("noticias", "Noticia")

    for noticia in Noticia.objects.all():
        texto = f"{noticia.titulo} {noticia.descripcion} {noticia.contenido or ''}".lower()
        texto = unicodedata.normalize("NFD", texto)
        texto = "".join(char for char in texto if unicodedata.category(char) != "Mn")

        noticia.violencia_fisica = bool(
            re.search(r"\b(golpe|agresion|agresion fisica|herida|lesion|maltrato fisico|arma blanca)\b", texto)
        )
        noticia.violencia_psicologica = bool(
            re.search(r"\b(amenaza|amenazas|insulto|intimidacion|humillacion|control|hostigamiento|manipulacion)\b", texto)
        )
        noticia.violencia_sexual = bool(re.search(r"\b(abuso sexual|violacion|acoso sexual)\b", texto))
        noticia.violencia_economica = bool(
            re.search(r"\b(control economico|dinero|dependencia economica|ingresos|recursos)\b", texto)
        )
        noticia.violencia_patrimonial = bool(
            re.search(r"\b(destruccion de bienes|retencion de documentos|dano patrimonial)\b", texto)
        )
        noticia.feminicidio = bool(re.search(r"\b(feminicidio|asesinada|hallada sin vida)\b", texto))

        if re.search(r"\b(pareja|expareja|novio|novia|esposo|esposa)\b", texto):
            noticia.ambito_violencia = "pareja"
        elif re.search(r"\b(familia|familiar|hogar|padre|madre|hermano|hermana)\b", texto):
            noticia.ambito_violencia = "familiar"
        elif re.search(r"\b(jefe|empresa|laboral|trabajo|institucion|ministerio)\b", texto):
            noticia.ambito_violencia = "institucional"
        elif re.search(r"\b(calle|via publica|transporte publico|bus|vecinos|comunidad|barrio)\b", texto):
            noticia.ambito_violencia = "comunitario"
        else:
            noticia.ambito_violencia = "otro"

        if noticia.feminicidio:
            noticia.nivel_riesgo = "critico"
        elif noticia.violencia_fisica or noticia.violencia_sexual:
            noticia.nivel_riesgo = "alto"
        elif noticia.violencia_psicologica:
            noticia.nivel_riesgo = "medio"
        else:
            noticia.nivel_riesgo = "bajo"

        noticia.save(
            update_fields=[
                "violencia_fisica",
                "violencia_psicologica",
                "violencia_sexual",
                "violencia_economica",
                "violencia_patrimonial",
                "feminicidio",
                "ambito_violencia",
                "nivel_riesgo",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("noticias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="ambito_violencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("familiar", "Familiar"),
                    ("pareja", "Pareja"),
                    ("comunitario", "Comunitario"),
                    ("institucional", "Institucional"),
                    ("otro", "Otro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="feminicidio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noticia",
            name="violencia_economica",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noticia",
            name="violencia_fisica",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noticia",
            name="violencia_patrimonial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noticia",
            name="violencia_psicologica",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noticia",
            name="violencia_sexual",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="nivel_riesgo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bajo", "Bajo"),
                    ("medio", "Medio"),
                    ("alto", "Alto"),
                    ("critico", "Critico"),
                ],
                max_length=10,
            ),
        ),
        migrations.RunPython(poblar_nuevos_campos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="noticia",
            name="tipo_violencia",
        ),
    ]
