# Generated by Django 6.0.3 on 2026-03-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_remove_noticia_tipo_violencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
