# Generated by Django 6.0.3 on 2026-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='es_prueba',
            field=models.BooleanField(default=False),
        ),
    ]
