# Generated by Django 6.0.3 on 2026-04-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_noticias', models.IntegerField(default=0)),
                ('total_verificadas', models.IntegerField(default=0)),
                ('violencia_fisica_count', models.IntegerField(default=0)),
                ('violencia_psicologica_count', models.IntegerField(default=0)),
                ('violencia_sexual_count', models.IntegerField(default=0)),
                ('violencia_economica_count', models.IntegerField(default=0)),
                ('violencia_patrimonial_count', models.IntegerField(default=0)),
                ('feminicidio_count', models.IntegerField(default=0)),
                ('ambito_familiar_count', models.IntegerField(default=0)),
                ('ambito_pareja_count', models.IntegerField(default=0)),
                ('ambito_comunitario_count', models.IntegerField(default=0)),
                ('ambito_institucional_count', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estadística de Resumen',
                'verbose_name_plural': 'Estadísticas de Resumen',
            },
        ),
    ]
